/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryCategory = IDL.Variant({
  'Men' : IDL.Null,
  'Kids' : IDL.Null,
  'Women' : IDL.Null,
  'Custom' : IDL.Null,
  'Featured' : IDL.Null,
});
export const CreateGalleryItemArgs = IDL.Record({
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : GalleryCategory,
});
export const GalleryItemId = IDL.Nat;
export const Timestamp = IDL.Int;
export const GalleryItem = IDL.Record({
  'id' : GalleryItemId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'category' : GalleryCategory,
});
export const ReviewId = IDL.Nat;
export const UserId = IDL.Principal;
export const OrderId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'comment' : IDL.Text,
  'approved' : IDL.Bool,
  'rating' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'Stitching' : IDL.Null,
  'Delivered' : IDL.Null,
  'Ready' : IDL.Null,
  'Received' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const Measurement = IDL.Record({
  'bust' : IDL.Opt(IDL.Nat),
  'hips' : IDL.Opt(IDL.Nat),
  'sleeve' : IDL.Opt(IDL.Nat),
  'shoulder' : IDL.Opt(IDL.Nat),
  'length' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
  'waist' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
});
export const ServiceId = IDL.Nat;
export const CartItem = IDL.Record({
  'serviceName' : IDL.Text,
  'addons' : IDL.Vec(IDL.Text),
  'quantity' : IDL.Nat,
  'serviceId' : ServiceId,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'tailorId' : IDL.Opt(UserId),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'measurements' : Measurement,
  'totalAmount' : IDL.Nat,
  'address' : Address,
  'items' : IDL.Vec(CartItem),
});
export const CreateCouponArgs = IDL.Record({
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
});
export const CouponId = IDL.Nat;
export const Coupon = IDL.Record({
  'id' : CouponId,
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const CreateOrderArgs = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'measurements' : Measurement,
  'totalAmount' : IDL.Nat,
  'address' : Address,
  'items' : IDL.Vec(CartItem),
});
export const CreateReviewArgs = IDL.Record({
  'orderId' : OrderId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Addon = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const ServiceCategory = IDL.Variant({
  'Men' : IDL.Null,
  'Kids' : IDL.Null,
  'Women' : IDL.Null,
  'Custom' : IDL.Null,
});
export const CreateServiceArgs = IDL.Record({
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'deliveryDays' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'addons' : IDL.Vec(Addon),
  'category' : ServiceCategory,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'fabricOptions' : IDL.Vec(IDL.Text),
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'deliveryDays' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'addons' : IDL.Vec(Addon),
  'category' : ServiceCategory,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'fabricOptions' : IDL.Vec(IDL.Text),
});
export const CreateTailorArgs = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'specialization' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});
export const Tailor = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'ordersAssigned' : IDL.Vec(OrderId),
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'specialization' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'customersCount' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'Customer' : IDL.Null,
  'Staff' : IDL.Null,
  'Admin' : IDL.Null,
  'Tailor' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'savedMeasurements' : IDL.Opt(Measurement),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateProfileArgs = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateServiceArgs = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'deliveryDays' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'addons' : IDL.Vec(Addon),
  'category' : ServiceCategory,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'fabricOptions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addGalleryItem' : IDL.Func([CreateGalleryItemArgs], [GalleryItem], []),
  'approveReview' : IDL.Func([ReviewId], [IDL.Opt(Review)], []),
  'assignTailor' : IDL.Func([OrderId, UserId], [IDL.Opt(Order)], []),
  'createCoupon' : IDL.Func([CreateCouponArgs], [Coupon], []),
  'createOrder' : IDL.Func([CreateOrderArgs], [Order], []),
  'createReview' : IDL.Func([CreateReviewArgs], [Review], []),
  'createService' : IDL.Func([CreateServiceArgs], [Service], []),
  'createTailor' : IDL.Func([CreateTailorArgs], [Tailor], []),
  'deleteCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
  'deleteGalleryItem' : IDL.Func([GalleryItemId], [IDL.Bool], []),
  'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
  'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getMyProfile' : IDL.Func([], [User], []),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'getServiceBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getTailor' : IDL.Func([UserId], [IDL.Opt(Tailor)], ['query']),
  'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'listGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listTailors' : IDL.Func([], [IDL.Vec(Tailor)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'saveMeasurements' : IDL.Func([Measurement], [IDL.Opt(User)], []),
  'toggleCoupon' : IDL.Func([CouponId], [IDL.Opt(Coupon)], []),
  'trackOrder' : IDL.Func([OrderId], [IDL.Opt(OrderStatus)], ['query']),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProfile' : IDL.Func([UpdateProfileArgs], [IDL.Opt(User)], []),
  'updateService' : IDL.Func([UpdateServiceArgs], [IDL.Opt(Service)], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryCategory = IDL.Variant({
    'Men' : IDL.Null,
    'Kids' : IDL.Null,
    'Women' : IDL.Null,
    'Custom' : IDL.Null,
    'Featured' : IDL.Null,
  });
  const CreateGalleryItemArgs = IDL.Record({
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : GalleryCategory,
  });
  const GalleryItemId = IDL.Nat;
  const Timestamp = IDL.Int;
  const GalleryItem = IDL.Record({
    'id' : GalleryItemId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'category' : GalleryCategory,
  });
  const ReviewId = IDL.Nat;
  const UserId = IDL.Principal;
  const OrderId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'orderId' : OrderId,
    'comment' : IDL.Text,
    'approved' : IDL.Bool,
    'rating' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'Stitching' : IDL.Null,
    'Delivered' : IDL.Null,
    'Ready' : IDL.Null,
    'Received' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const Measurement = IDL.Record({
    'bust' : IDL.Opt(IDL.Nat),
    'hips' : IDL.Opt(IDL.Nat),
    'sleeve' : IDL.Opt(IDL.Nat),
    'shoulder' : IDL.Opt(IDL.Nat),
    'length' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
    'waist' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const ServiceId = IDL.Nat;
  const CartItem = IDL.Record({
    'serviceName' : IDL.Text,
    'addons' : IDL.Vec(IDL.Text),
    'quantity' : IDL.Nat,
    'serviceId' : ServiceId,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'tailorId' : IDL.Opt(UserId),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'measurements' : Measurement,
    'totalAmount' : IDL.Nat,
    'address' : Address,
    'items' : IDL.Vec(CartItem),
  });
  const CreateCouponArgs = IDL.Record({
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
  });
  const CouponId = IDL.Nat;
  const Coupon = IDL.Record({
    'id' : CouponId,
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const CreateOrderArgs = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'measurements' : Measurement,
    'totalAmount' : IDL.Nat,
    'address' : Address,
    'items' : IDL.Vec(CartItem),
  });
  const CreateReviewArgs = IDL.Record({
    'orderId' : OrderId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Addon = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ServiceCategory = IDL.Variant({
    'Men' : IDL.Null,
    'Kids' : IDL.Null,
    'Women' : IDL.Null,
    'Custom' : IDL.Null,
  });
  const CreateServiceArgs = IDL.Record({
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'deliveryDays' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'addons' : IDL.Vec(Addon),
    'category' : ServiceCategory,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'fabricOptions' : IDL.Vec(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'deliveryDays' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'addons' : IDL.Vec(Addon),
    'category' : ServiceCategory,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'fabricOptions' : IDL.Vec(IDL.Text),
  });
  const CreateTailorArgs = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'specialization' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  const Tailor = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'ordersAssigned' : IDL.Vec(OrderId),
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'specialization' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'customersCount' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'Customer' : IDL.Null,
    'Staff' : IDL.Null,
    'Admin' : IDL.Null,
    'Tailor' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'savedMeasurements' : IDL.Opt(Measurement),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateProfileArgs = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateServiceArgs = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'deliveryDays' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'addons' : IDL.Vec(Addon),
    'category' : ServiceCategory,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'fabricOptions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addGalleryItem' : IDL.Func([CreateGalleryItemArgs], [GalleryItem], []),
    'approveReview' : IDL.Func([ReviewId], [IDL.Opt(Review)], []),
    'assignTailor' : IDL.Func([OrderId, UserId], [IDL.Opt(Order)], []),
    'createCoupon' : IDL.Func([CreateCouponArgs], [Coupon], []),
    'createOrder' : IDL.Func([CreateOrderArgs], [Order], []),
    'createReview' : IDL.Func([CreateReviewArgs], [Review], []),
    'createService' : IDL.Func([CreateServiceArgs], [Service], []),
    'createTailor' : IDL.Func([CreateTailorArgs], [Tailor], []),
    'deleteCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
    'deleteGalleryItem' : IDL.Func([GalleryItemId], [IDL.Bool], []),
    'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
    'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getMyProfile' : IDL.Func([], [User], []),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'getServiceBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getTailor' : IDL.Func([UserId], [IDL.Opt(Tailor)], ['query']),
    'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'listGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listTailors' : IDL.Func([], [IDL.Vec(Tailor)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'saveMeasurements' : IDL.Func([Measurement], [IDL.Opt(User)], []),
    'toggleCoupon' : IDL.Func([CouponId], [IDL.Opt(Coupon)], []),
    'trackOrder' : IDL.Func([OrderId], [IDL.Opt(OrderStatus)], ['query']),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProfile' : IDL.Func([UpdateProfileArgs], [IDL.Opt(User)], []),
    'updateService' : IDL.Func([UpdateServiceArgs], [IDL.Opt(Service)], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };