/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Addon { 'id' : bigint, 'name' : string, 'price' : bigint }
export interface Address {
  'street' : string,
  'country' : string,
  'city' : string,
  'zipCode' : string,
  'state' : string,
}
export interface AdminStats {
  'totalOrders' : bigint,
  'customersCount' : bigint,
  'pendingOrders' : bigint,
  'totalRevenue' : bigint,
}
export interface CartItem {
  'serviceName' : string,
  'addons' : Array<string>,
  'quantity' : bigint,
  'serviceId' : ServiceId,
  'price' : bigint,
}
export interface Coupon {
  'id' : CouponId,
  'code' : string,
  'createdAt' : Timestamp,
  'discountPercent' : bigint,
  'isActive' : boolean,
}
export type CouponId = bigint;
export interface CreateCouponArgs {
  'code' : string,
  'discountPercent' : bigint,
}
export interface CreateGalleryItemArgs {
  'title' : string,
  'imageUrl' : string,
  'category' : GalleryCategory,
}
export interface CreateOrderArgs {
  'couponCode' : [] | [string],
  'measurements' : Measurement,
  'totalAmount' : bigint,
  'address' : Address,
  'items' : Array<CartItem>,
}
export interface CreateReviewArgs {
  'orderId' : OrderId,
  'comment' : string,
  'rating' : bigint,
}
export interface CreateServiceArgs {
  'name' : string,
  'slug' : string,
  'deliveryDays' : bigint,
  'description' : string,
  'imageUrl' : string,
  'addons' : Array<Addon>,
  'category' : ServiceCategory,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'fabricOptions' : Array<string>,
}
export interface CreateTailorArgs {
  'principal' : UserId,
  'name' : string,
  'email' : string,
  'specialization' : Array<string>,
  'phone' : string,
}
export type GalleryCategory = { 'Men' : null } |
  { 'Kids' : null } |
  { 'Women' : null } |
  { 'Custom' : null } |
  { 'Featured' : null };
export interface GalleryItem {
  'id' : GalleryItemId,
  'title' : string,
  'createdAt' : Timestamp,
  'imageUrl' : string,
  'category' : GalleryCategory,
}
export type GalleryItemId = bigint;
export interface Measurement {
  'bust' : [] | [bigint],
  'hips' : [] | [bigint],
  'sleeve' : [] | [bigint],
  'shoulder' : [] | [bigint],
  'length' : [] | [bigint],
  'notes' : string,
  'waist' : [] | [bigint],
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'tailorId' : [] | [UserId],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'measurements' : Measurement,
  'totalAmount' : bigint,
  'address' : Address,
  'items' : Array<CartItem>,
}
export type OrderId = bigint;
export type OrderStatus = { 'Stitching' : null } |
  { 'Delivered' : null } |
  { 'Ready' : null } |
  { 'Received' : null } |
  { 'InProgress' : null };
export interface Review {
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'comment' : string,
  'approved' : boolean,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'slug' : string,
  'deliveryDays' : bigint,
  'description' : string,
  'imageUrl' : string,
  'addons' : Array<Addon>,
  'category' : ServiceCategory,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'fabricOptions' : Array<string>,
}
export type ServiceCategory = { 'Men' : null } |
  { 'Kids' : null } |
  { 'Women' : null } |
  { 'Custom' : null };
export type ServiceId = bigint;
export interface Tailor {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'ordersAssigned' : Array<OrderId>,
  'isActive' : boolean,
  'email' : string,
  'specialization' : Array<string>,
  'phone' : string,
}
export type Timestamp = bigint;
export interface UpdateProfileArgs {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface UpdateServiceArgs {
  'id' : ServiceId,
  'name' : string,
  'slug' : string,
  'deliveryDays' : bigint,
  'description' : string,
  'imageUrl' : string,
  'addons' : Array<Addon>,
  'category' : ServiceCategory,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'fabricOptions' : Array<string>,
}
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'savedMeasurements' : [] | [Measurement],
  'email' : string,
  'phone' : string,
}
export type UserId = Principal;
export type UserRole = { 'Customer' : null } |
  { 'Staff' : null } |
  { 'Admin' : null } |
  { 'Tailor' : null };
export interface _SERVICE {
  'addGalleryItem' : ActorMethod<[CreateGalleryItemArgs], GalleryItem>,
  'approveReview' : ActorMethod<[ReviewId], [] | [Review]>,
  'assignTailor' : ActorMethod<[OrderId, UserId], [] | [Order]>,
  'createCoupon' : ActorMethod<[CreateCouponArgs], Coupon>,
  'createOrder' : ActorMethod<[CreateOrderArgs], Order>,
  'createReview' : ActorMethod<[CreateReviewArgs], Review>,
  'createService' : ActorMethod<[CreateServiceArgs], Service>,
  'createTailor' : ActorMethod<[CreateTailorArgs], Tailor>,
  'deleteCoupon' : ActorMethod<[CouponId], boolean>,
  'deleteGalleryItem' : ActorMethod<[GalleryItemId], boolean>,
  'deleteReview' : ActorMethod<[ReviewId], boolean>,
  'deleteService' : ActorMethod<[ServiceId], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getMyProfile' : ActorMethod<[], User>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'getServiceBySlug' : ActorMethod<[string], [] | [Service]>,
  'getTailor' : ActorMethod<[UserId], [] | [Tailor]>,
  'listAllReviews' : ActorMethod<[], Array<Review>>,
  'listApprovedReviews' : ActorMethod<[], Array<Review>>,
  'listCoupons' : ActorMethod<[], Array<Coupon>>,
  'listGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listTailors' : ActorMethod<[], Array<Tailor>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'saveMeasurements' : ActorMethod<[Measurement], [] | [User]>,
  'toggleCoupon' : ActorMethod<[CouponId], [] | [Coupon]>,
  'trackOrder' : ActorMethod<[OrderId], [] | [OrderStatus]>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProfile' : ActorMethod<[UpdateProfileArgs], [] | [User]>,
  'updateService' : ActorMethod<[UpdateServiceArgs], [] | [Service]>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];