/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Address {
    street: string;
    country: string;
    city: string;
    zipCode: string;
    state: string;
}
export type Timestamp = bigint;
export interface Tailor {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    ordersAssigned: Array<OrderId>;
    isActive: boolean;
    email: string;
    specialization: Array<string>;
    phone: string;
}
export interface UpdateProfileArgs {
    name: string;
    email: string;
    phone: string;
}
export interface UpdateServiceArgs {
    id: ServiceId;
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<Addon>;
    category: ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
}
export interface CreateGalleryItemArgs {
    title: string;
    imageUrl: string;
    category: GalleryCategory;
}
export type ReviewId = bigint;
export type CouponId = bigint;
export interface CreateReviewArgs {
    orderId: OrderId;
    comment: string;
    rating: bigint;
}
export interface CreateOrderArgs {
    couponCode?: string;
    measurements: Measurement;
    totalAmount: bigint;
    address: Address;
    items: Array<CartItem>;
}
export type ServiceId = bigint;
export interface Review {
    id: ReviewId;
    userId: UserId;
    createdAt: Timestamp;
    orderId: OrderId;
    comment: string;
    approved: boolean;
    rating: bigint;
}
export interface User {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    savedMeasurements?: Measurement;
    email: string;
    phone: string;
}
export interface Coupon {
    id: CouponId;
    code: string;
    createdAt: Timestamp;
    discountPercent: bigint;
    isActive: boolean;
}
export interface Service {
    id: ServiceId;
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<Addon>;
    category: ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
}
export interface Addon {
    id: bigint;
    name: string;
    price: bigint;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    couponCode?: string;
    tailorId?: UserId;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    measurements: Measurement;
    totalAmount: bigint;
    address: Address;
    items: Array<CartItem>;
}
export interface CreateServiceArgs {
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<Addon>;
    category: ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
}
export type UserId = Principal;
export interface CreateTailorArgs {
    principal: UserId;
    name: string;
    email: string;
    specialization: Array<string>;
    phone: string;
}
export interface AdminStats {
    totalOrders: bigint;
    customersCount: bigint;
    pendingOrders: bigint;
    totalRevenue: bigint;
}
export type GalleryItemId = bigint;
export interface Measurement {
    bust?: bigint;
    hips?: bigint;
    sleeve?: bigint;
    shoulder?: bigint;
    length?: bigint;
    notes: string;
    waist?: bigint;
}
export interface CartItem {
    serviceName: string;
    addons: Array<string>;
    quantity: bigint;
    serviceId: ServiceId;
    price: bigint;
}
export interface GalleryItem {
    id: GalleryItemId;
    title: string;
    createdAt: Timestamp;
    imageUrl: string;
    category: GalleryCategory;
}
export type OrderId = bigint;
export interface CreateCouponArgs {
    code: string;
    discountPercent: bigint;
}
export enum GalleryCategory {
    Men = "Men",
    Kids = "Kids",
    Women = "Women",
    Custom = "Custom",
    Featured = "Featured"
}
export enum OrderStatus {
    Stitching = "Stitching",
    Delivered = "Delivered",
    Ready = "Ready",
    Received = "Received",
    InProgress = "InProgress"
}
export enum ServiceCategory {
    Men = "Men",
    Kids = "Kids",
    Women = "Women",
    Custom = "Custom"
}
export enum UserRole {
    Customer = "Customer",
    Staff = "Staff",
    Admin = "Admin",
    Tailor = "Tailor"
}
export interface backendInterface {
    addGalleryItem(args: CreateGalleryItemArgs): Promise<GalleryItem>;
    approveReview(id: ReviewId): Promise<Review | null>;
    assignTailor(orderId: OrderId, tailorId: UserId): Promise<Order | null>;
    createCoupon(args: CreateCouponArgs): Promise<Coupon>;
    createOrder(args: CreateOrderArgs): Promise<Order>;
    createReview(args: CreateReviewArgs): Promise<Review>;
    createService(args: CreateServiceArgs): Promise<Service>;
    createTailor(args: CreateTailorArgs): Promise<Tailor>;
    deleteCoupon(id: CouponId): Promise<boolean>;
    deleteGalleryItem(id: GalleryItemId): Promise<boolean>;
    deleteReview(id: ReviewId): Promise<boolean>;
    deleteService(id: ServiceId): Promise<boolean>;
    getAdminStats(): Promise<AdminStats>;
    getMyProfile(): Promise<User>;
    getOrder(id: OrderId): Promise<Order | null>;
    getService(id: ServiceId): Promise<Service | null>;
    getServiceBySlug(slug: string): Promise<Service | null>;
    getTailor(id: UserId): Promise<Tailor | null>;
    listAllReviews(): Promise<Array<Review>>;
    listApprovedReviews(): Promise<Array<Review>>;
    listCoupons(): Promise<Array<Coupon>>;
    listGalleryItems(): Promise<Array<GalleryItem>>;
    listMyOrders(): Promise<Array<Order>>;
    listOrders(): Promise<Array<Order>>;
    listServices(): Promise<Array<Service>>;
    listTailors(): Promise<Array<Tailor>>;
    listUsers(): Promise<Array<User>>;
    saveMeasurements(measurements: Measurement): Promise<User | null>;
    toggleCoupon(id: CouponId): Promise<Coupon | null>;
    trackOrder(id: OrderId): Promise<OrderStatus | null>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
    updateProfile(args: UpdateProfileArgs): Promise<User | null>;
    updateService(args: UpdateServiceArgs): Promise<Service | null>;
    validateCoupon(code: string): Promise<Coupon | null>;
}
import type { Addon as _Addon, Address as _Address, CartItem as _CartItem, Coupon as _Coupon, CreateGalleryItemArgs as _CreateGalleryItemArgs, CreateOrderArgs as _CreateOrderArgs, CreateServiceArgs as _CreateServiceArgs, GalleryCategory as _GalleryCategory, GalleryItem as _GalleryItem, GalleryItemId as _GalleryItemId, Measurement as _Measurement, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Review as _Review, Service as _Service, ServiceCategory as _ServiceCategory, ServiceId as _ServiceId, Tailor as _Tailor, Timestamp as _Timestamp, UpdateServiceArgs as _UpdateServiceArgs, User as _User, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGalleryItem(arg0: CreateGalleryItemArgs): Promise<GalleryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(to_candid_CreateGalleryItemArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GalleryItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(to_candid_CreateGalleryItemArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GalleryItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveReview(arg0: ReviewId): Promise<Review | null> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReview(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReview(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignTailor(arg0: OrderId, arg1: UserId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTailor(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTailor(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCoupon(arg0: CreateCouponArgs): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0);
            return result;
        }
    }
    async createOrder(arg0: CreateOrderArgs): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderArgs_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderArgs_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReview(arg0: CreateReviewArgs): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0);
            return result;
        }
    }
    async createService(arg0: CreateServiceArgs): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_CreateServiceArgs_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Service_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_CreateServiceArgs_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Service_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTailor(arg0: CreateTailorArgs): Promise<Tailor> {
        if (this.processError) {
            try {
                const result = await this.actor.createTailor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTailor(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: CouponId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: GalleryItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteReview(arg0: ReviewId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteService(arg0: ServiceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getMyProfile(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_User_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_User_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceBySlug(arg0: string): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceBySlug(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceBySlug(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTailor(arg0: UserId): Promise<Tailor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailor(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailor(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllReviews();
            return result;
        }
    }
    async listApprovedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovedReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovedReviews();
            return result;
        }
    }
    async listCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoupons();
            return result;
        }
    }
    async listGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryItems();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryItems();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTailors(): Promise<Array<Tailor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTailors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTailors();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMeasurements(arg0: Measurement): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMeasurements(to_candid_Measurement_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMeasurements(to_candid_Measurement_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCoupon(arg0: CouponId): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCoupon(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCoupon(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackOrder(arg0: OrderId): Promise<OrderStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.trackOrder(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackOrder(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileArgs): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateService(arg0: UpdateServiceArgs): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(to_candid_UpdateServiceArgs_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(to_candid_UpdateServiceArgs_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_GalleryCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryCategory): GalleryCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): GalleryItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Measurement_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Measurement): Measurement {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_User_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Measurement]): Measurement | null {
    return value.length === 0 ? null : from_candid_Measurement_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tailor]): Tailor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderStatus]): OrderStatus | null {
    return value.length === 0 ? null : from_candid_OrderStatus_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Review]): Review | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    couponCode: [] | [string];
    tailorId: [] | [_UserId];
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    measurements: _Measurement;
    totalAmount: bigint;
    address: _Address;
    items: Array<_CartItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    couponCode?: string;
    tailorId?: UserId;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    measurements: Measurement;
    totalAmount: bigint;
    address: Address;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n13(_uploadFile, _downloadFile, value.status),
        couponCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.couponCode)),
        tailorId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tailorId)),
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        measurements: from_candid_Measurement_n17(_uploadFile, _downloadFile, value.measurements),
        totalAmount: value.totalAmount,
        address: value.address,
        items: value.items
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bust: [] | [bigint];
    hips: [] | [bigint];
    sleeve: [] | [bigint];
    shoulder: [] | [bigint];
    length: [] | [bigint];
    notes: string;
    waist: [] | [bigint];
}): {
    bust?: bigint;
    hips?: bigint;
    sleeve?: bigint;
    shoulder?: bigint;
    length?: bigint;
    notes: string;
    waist?: bigint;
} {
    return {
        bust: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.bust)),
        hips: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.hips)),
        sleeve: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.sleeve)),
        shoulder: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.shoulder)),
        length: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.length)),
        notes: value.notes,
        waist: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.waist))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ServiceId;
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<_Addon>;
    category: _ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
}): {
    id: ServiceId;
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<Addon>;
    category: ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
} {
    return {
        id: value.id,
        name: value.name,
        slug: value.slug,
        deliveryDays: value.deliveryDays,
        description: value.description,
        imageUrl: value.imageUrl,
        addons: value.addons,
        category: from_candid_ServiceCategory_n30(_uploadFile, _downloadFile, value.category),
        priceMax: value.priceMax,
        priceMin: value.priceMin,
        fabricOptions: value.fabricOptions
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    savedMeasurements: [] | [_Measurement];
    email: string;
    phone: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    savedMeasurements?: Measurement;
    email: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n34(_uploadFile, _downloadFile, value.role),
        savedMeasurements: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.savedMeasurements)),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GalleryItemId;
    title: string;
    createdAt: _Timestamp;
    imageUrl: string;
    category: _GalleryCategory;
}): {
    id: GalleryItemId;
    title: string;
    createdAt: Timestamp;
    imageUrl: string;
    category: GalleryCategory;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        imageUrl: value.imageUrl,
        category: from_candid_GalleryCategory_n7(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Stitching: null;
} | {
    Delivered: null;
} | {
    Ready: null;
} | {
    Received: null;
} | {
    InProgress: null;
}): OrderStatus {
    return "Stitching" in value ? OrderStatus.Stitching : "Delivered" in value ? OrderStatus.Delivered : "Ready" in value ? OrderStatus.Ready : "Received" in value ? OrderStatus.Received : "InProgress" in value ? OrderStatus.InProgress : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Men: null;
} | {
    Kids: null;
} | {
    Women: null;
} | {
    Custom: null;
}): ServiceCategory {
    return "Men" in value ? ServiceCategory.Men : "Kids" in value ? ServiceCategory.Kids : "Women" in value ? ServiceCategory.Women : "Custom" in value ? ServiceCategory.Custom : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Customer: null;
} | {
    Staff: null;
} | {
    Admin: null;
} | {
    Tailor: null;
}): UserRole {
    return "Customer" in value ? UserRole.Customer : "Staff" in value ? UserRole.Staff : "Admin" in value ? UserRole.Admin : "Tailor" in value ? UserRole.Tailor : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Men: null;
} | {
    Kids: null;
} | {
    Women: null;
} | {
    Custom: null;
} | {
    Featured: null;
}): GalleryCategory {
    return "Men" in value ? GalleryCategory.Men : "Kids" in value ? GalleryCategory.Kids : "Women" in value ? GalleryCategory.Women : "Custom" in value ? GalleryCategory.Custom : "Featured" in value ? GalleryCategory.Featured : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Array<GalleryItem> {
    return value.map((x)=>from_candid_GalleryItem_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n32(_uploadFile, _downloadFile, x));
}
function to_candid_CreateGalleryItemArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGalleryItemArgs): _CreateGalleryItemArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderArgs_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderArgs): _CreateOrderArgs {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_CreateServiceArgs_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateServiceArgs): _CreateServiceArgs {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_GalleryCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryCategory): _GalleryCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Measurement_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Measurement): _Measurement {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateServiceArgs_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateServiceArgs): _UpdateServiceArgs {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageUrl: string;
    category: GalleryCategory;
}): {
    title: string;
    imageUrl: string;
    category: _GalleryCategory;
} {
    return {
        title: value.title,
        imageUrl: value.imageUrl,
        category: to_candid_GalleryCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    measurements: Measurement;
    totalAmount: bigint;
    address: Address;
    items: Array<CartItem>;
}): {
    couponCode: [] | [string];
    measurements: _Measurement;
    totalAmount: bigint;
    address: _Address;
    items: Array<_CartItem>;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        measurements: to_candid_Measurement_n22(_uploadFile, _downloadFile, value.measurements),
        totalAmount: value.totalAmount,
        address: value.address,
        items: value.items
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bust?: bigint;
    hips?: bigint;
    sleeve?: bigint;
    shoulder?: bigint;
    length?: bigint;
    notes: string;
    waist?: bigint;
}): {
    bust: [] | [bigint];
    hips: [] | [bigint];
    sleeve: [] | [bigint];
    shoulder: [] | [bigint];
    length: [] | [bigint];
    notes: string;
    waist: [] | [bigint];
} {
    return {
        bust: value.bust ? candid_some(value.bust) : candid_none(),
        hips: value.hips ? candid_some(value.hips) : candid_none(),
        sleeve: value.sleeve ? candid_some(value.sleeve) : candid_none(),
        shoulder: value.shoulder ? candid_some(value.shoulder) : candid_none(),
        length: value.length ? candid_some(value.length) : candid_none(),
        notes: value.notes,
        waist: value.waist ? candid_some(value.waist) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<Addon>;
    category: ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
}): {
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<_Addon>;
    category: _ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
} {
    return {
        name: value.name,
        slug: value.slug,
        deliveryDays: value.deliveryDays,
        description: value.description,
        imageUrl: value.imageUrl,
        addons: value.addons,
        category: to_candid_ServiceCategory_n26(_uploadFile, _downloadFile, value.category),
        priceMax: value.priceMax,
        priceMin: value.priceMin,
        fabricOptions: value.fabricOptions
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ServiceId;
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<Addon>;
    category: ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
}): {
    id: _ServiceId;
    name: string;
    slug: string;
    deliveryDays: bigint;
    description: string;
    imageUrl: string;
    addons: Array<_Addon>;
    category: _ServiceCategory;
    priceMax: bigint;
    priceMin: bigint;
    fabricOptions: Array<string>;
} {
    return {
        id: value.id,
        name: value.name,
        slug: value.slug,
        deliveryDays: value.deliveryDays,
        description: value.description,
        imageUrl: value.imageUrl,
        addons: value.addons,
        category: to_candid_ServiceCategory_n26(_uploadFile, _downloadFile, value.category),
        priceMax: value.priceMax,
        priceMin: value.priceMin,
        fabricOptions: value.fabricOptions
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    Men: null;
} | {
    Kids: null;
} | {
    Women: null;
} | {
    Custom: null;
} {
    return value == ServiceCategory.Men ? {
        Men: null
    } : value == ServiceCategory.Kids ? {
        Kids: null
    } : value == ServiceCategory.Women ? {
        Women: null
    } : value == ServiceCategory.Custom ? {
        Custom: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryCategory): {
    Men: null;
} | {
    Kids: null;
} | {
    Women: null;
} | {
    Custom: null;
} | {
    Featured: null;
} {
    return value == GalleryCategory.Men ? {
        Men: null
    } : value == GalleryCategory.Kids ? {
        Kids: null
    } : value == GalleryCategory.Women ? {
        Women: null
    } : value == GalleryCategory.Custom ? {
        Custom: null
    } : value == GalleryCategory.Featured ? {
        Featured: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Stitching: null;
} | {
    Delivered: null;
} | {
    Ready: null;
} | {
    Received: null;
} | {
    InProgress: null;
} {
    return value == OrderStatus.Stitching ? {
        Stitching: null
    } : value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Ready ? {
        Ready: null
    } : value == OrderStatus.Received ? {
        Received: null
    } : value == OrderStatus.InProgress ? {
        InProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
